export interface WebMcpPromptBlocks { role: string; task: string; input: string; tools: string; output: string; exampleOutput: string }
export interface WebMcpPromptDefinition { name: string; title: string; description: string; runtimeDescription: string; blocks: WebMcpPromptBlocks; exampleInput: unknown }
type Blocks = { name: string; title: string } & WebMcpPromptBlocks
const role = 'You are a browser agent collaborating with a person inside the ProjectV2 spatial editor. Use stable semantic references, local model metres, straight-edged polygons and reversible ghost variants.'
const result = 'Call this WebMCP tool with a JSON object. Read content[0].text as JSON containing status, projectRevision and summary plus tool-specific fields. Never treat visible report image object URLs as tool output.'
const proposalOutput = `${result} A valid change returns status "variant_created" and variantRef; it does not modify the committed project.`
const proposalTools = 'Call get_project_state first. Create a ghost variant, compare it if useful, and call manage_variant with action `request-apply` only when the person should review it. Never claim the variant is committed before approval.'
const format = ({ role: r, task, input, tools, output, exampleOutput }: Blocks) => `<role>\n${r}\n</role>\n\n<task>\n${task}\n</task>\n\n<input>\n${input}\n</input>\n\n<tools>\n${tools}\n</tools>\n\n<output>\n${output}\n</output>\n\n<example_output>\n${exampleOutput}\n</example_output>`
const define = (blocks: Blocks): WebMcpPromptDefinition => ({
  name: blocks.name,
  title: blocks.title,
  description: format(blocks),
  runtimeDescription: blocks.task,
  blocks: { role: blocks.role, task: blocks.task, input: blocks.input, tools: blocks.tools, output: blocks.output, exampleOutput: blocks.exampleOutput },
  exampleInput: JSON.parse(blocks.exampleOutput),
})
const proposal = (name: string, title: string, task: string, input: string, exampleOutput: string) => define({ name, title, role, task, input, tools: proposalTools, output: proposalOutput, exampleOutput })

export const webMcpFieldPrompts = {
  positionX: 'East-west local model coordinate in metres.', positionZ: 'North-south local model coordinate in metres.', semanticRef: 'Stable semantic reference such as building/main, storey/ground or wall/east.',
} as const

export const webMcpToolPrompts = {
  get_project_state: define({ name: 'get_project_state', title: 'Inspect ProjectV2', role, task: 'Read the committed V2 site, terrain, buildings, shared slabs, wall graph, spaces, openings, landscape, climate, evidence-linked planting recommendations, soil analysis, metrics and variants.', input: '`detail` (enum): `summary`, `site`, `structure`, `landscape`, or `full`. `landscape` returns placed landscape, climate and the planting guide, including documented soil findings, unknowns, required tests, preparation principles, vegetables and fruit trees.', tools: 'Use before proposing edits or requesting views. This is read-only. Treat conditional crop recommendations and unknown soil properties as constraints, not verified suitability.', output: result, exampleOutput: '{"detail":"landscape"}' }),
  get_proposals: define({ name: 'get_proposals', title: 'List or inspect proposals', role, task: 'Read persistent proposal history and draft change sets without changing project or review state.', input: 'Input is a JSON object. Optional `proposalRef` (string) returns one complete proposal audit. Optional `status` is `pending`, `approved`, `rejected`, or `stale` and filters list mode. Optional `includeDrafts` (boolean, default true) includes draft and stale change sets.', tools: 'This is read-only. Use `manage_variant` with action `request-apply` to reopen a current pending proposal for human review. Never treat an approved proposal as undo history or apply a stale proposal.', output: `${result} Returns counts by status, matching proposal records without embedded preview projects, and optional draft change sets.`, exampleOutput: '{"status":"pending","includeDrafts":true}' }),
  list_garden_fixtures: define({ name: 'list_garden_fixtures', title: 'List ready garden fixtures', role, task: 'Read the editor-owned fixture catalog for raised beds and standard crop rows, including semantic IDs and metre dimensions.', input: 'Input is an empty JSON object.', tools: 'Use before proposing garden fixtures. This is read-only. Use only returned catalog IDs; do not invent fixture types.', output: `${result} Returns data as an array of fixture definitions with id, name, category, description, widthM, depthM and heightM.`, exampleOutput: '{}' }),
  propose_site_update: proposal('propose_site_update', 'Propose site update', 'Change the straight-edged site boundary or site-north direction.', '`boundary` is an optional polygon; `northDegrees` is optional.', '{"northDegrees":-56.7}'),
  propose_terrain_update: proposal('propose_terrain_update', 'Propose terrain update', 'Replace terrain elevation controls used for support and planting elevation.', '`elevationPoints` is a non-empty array of `{x,z,elevation}`.', '{"elevationPoints":[{"x":0,"z":0,"elevation":242.1}]}'),
  propose_building_update: proposal('propose_building_update', 'Propose building update', 'Add, remove, move, rotate or restyle a building.', '`action`, `buildingRef`; optional `name`, `kind`, `architecturalStyle`, `position`, `rotationDegrees`.', '{"action":"move","buildingRef":"house/main","position":{"x":1,"z":-2}}'),
  propose_storey_update: proposal('propose_storey_update', 'Propose storey update', 'Add/remove a storey, change its clear height, or atomically extend an existing storey footprint. `extend-footprint` updates its shared slab, exterior wall graph, enclosed space and top-storey roof footprint in one ghost variant while reusing compatible walls and openings.', '`action`, `buildingRef`, `storeyRef`; optional `name`, `clearHeightM`. For `extend-footprint`, pass either the desired complete `footprint` or a non-overlapping adjacent `extensionFootprint`; optional `spaceRef`, `spaceName`, and `usage` describe the new enclosed extension space.', '{"action":"extend-footprint","buildingRef":"house/main","storeyRef":"house/main/storey-upper","extensionFootprint":[{"x":-8,"z":-5},{"x":8,"z":-5},{"x":8,"z":1},{"x":-2,"z":1},{"x":-8,"z":1}],"spaceRef":"house/main/storey-upper/space-wing","spaceName":"Upper wing","usage":"living"}'),
  propose_slab_update: proposal('propose_slab_update', 'Propose shared slab update', 'Edit a semantic slab once so it remains the upper floor and lower ceiling boundary.', '`action`, `buildingRef`, `slabRef`; optional `footprint`, `thicknessM`, `topElevationM`.', '{"action":"set-thickness","buildingRef":"house/main","slabRef":"storey/upper/base-slab","thicknessM":0.28}'),
  propose_space_update: proposal('propose_space_update', 'Propose polygonal space update', 'Add/remove a polygonal space, edit its straight-edged footprint or usage, or add a linked lowered ceiling finish.', '`action`, `buildingRef`, `storeyRef`, `spaceRef`; action fields include `name`, `usage`, `footprint`, `ceilingElevationM`.', '{"action":"set-lowered-ceiling","buildingRef":"house/main","storeyRef":"storey/ground","spaceRef":"space/living","ceilingElevationM":3.1}'),
  propose_wall_update: proposal('propose_wall_update', 'Propose shared wall update', 'Move or resize one wall in the shared wall graph.', '`action`, `buildingRef`, `wallRef`; optional `start`, `end`, `thicknessM`, `heightM`.', '{"action":"set-thickness","buildingRef":"house/main","wallRef":"wall/partition","thicknessM":0.16}'),
  propose_wall_opening_layout: proposal('propose_wall_opening_layout', 'Propose wall façade layout', 'Replace every opening on one wall with a complete façade preset. Use this when the person asks for a full glass wall, exactly two windows, one normal centered window, one tall balcony door, or a solid wall. The replacement is sized automatically to fit the selected wall.', '`buildingRef`, `wallRef`, and `preset`. Preset is `full-glass`, `two-windows`, `center-window`, `balcony-door`, or `solid-wall`. Use get_project_state with detail structure first to resolve the exact wall reference.', '{"buildingRef":"house/main","wallRef":"wall/courtyard-living","preset":"center-window"}'),
  propose_wall_finish_update: proposal('propose_wall_finish_update', 'Propose wall material and color', 'Apply an opaque semantic material and exact color to one wall or every exterior wall of a building. This changes wall surfaces only and does not add, remove, or resize openings.', 'Input is a JSON object with required `buildingRef` (string), `scope` (`wall` or `all-exterior`), `material` (`charred-timber`, `natural-timber`, `light-render`, `brick`, or `metal-panel`), and `colorHex` (six-digit hex string including `#`). `wallRef` (string) is required only when `scope` is `wall`. Call get_project_state with detail structure first to resolve semantic references.', '{"buildingRef":"house/main","scope":"all-exterior","material":"charred-timber","colorHex":"#242927"}'),
  propose_opening_update: proposal('propose_opening_update', 'Propose opening update', 'Add, remove, move or resize a door/window void hosted by a wall. Use get_project_state with detail structure first when the requested wall or opening reference is not known. A remove action closes the opening and reduces the wall window count.', '`action`, `buildingRef`, `wallRef`, `openingRef`; optional `kind`, `offsetM`, `widthM`, `heightM`, `sillM`.', '{"action":"remove","buildingRef":"house/main","wallRef":"wall/courtyard-living","openingRef":"opening/living-balcony-door"}'),
  propose_roof_update: proposal('propose_roof_update', 'Propose roof or segment update', 'Update, add, or atomically split semantic roof segments while preserving explicit support links, perpendicular ridge directions, finishes, and typed valley/intersection junctions.', 'Input is a JSON object with required `buildingRef` and `action` (`update`, `add-segment`, or `split-segment`; default `update`). For `update`, optional `roofRef` or `segmentRef` selects the complete roof or one segment; segment updates may set `footprint`, `ridgeDirection` (`x` or `z`), `storeyRef`, and `spaceRef`. For `add-segment`, require new `segmentRef`, polygon `footprint`, and `ridgeDirection`; optional support, geometry, elevation, and finish fields initialize it. For `split-segment`, require the malformed source `segmentRef`, `segments` with at least two complete replacement definitions (`segmentRef`, `footprint`, `ridgeDirection`, optional `storeyRef`, `spaceRef`, geometry, elevation, and finish), and `junctions` with stable `ref`, `type` (`valley` or `intersection`), and exactly two `segmentRefs`. Replacement fields omitted during a split inherit from the source segment. Common geometry fields are `roofType`, `pitchDegrees` (0–70), and `overhangM` (0–3). Use at most one vertical instruction: `baseElevationM`, `targetEavesElevationM`, `verticalDeltaM`, or `alignToSegmentRef` with optional `alignEdge` (`eaves` or `ridge`). Finish fields are `material` and six-digit `colorHex`; `synchronization` is `roof-only`, `roof-and-supporting-walls`, or `storey-height`.', '{"action":"split-segment","buildingRef":"house/main","segmentRef":"roof/main/segment-main","segments":[{"segmentRef":"roof/main/segment-original-wing","footprint":[{"x":-8,"z":1},{"x":-2,"z":1},{"x":-2,"z":10},{"x":-8,"z":10}],"ridgeDirection":"z","storeyRef":"house/main/storey-upper","spaceRef":"house/main/storey-upper/space-main","baseElevationM":6.55,"material":"standing-seam-metal","colorHex":"#2D3435"},{"segmentRef":"roof/main/segment-extended-wing","footprint":[{"x":-8,"z":-5},{"x":8,"z":-5},{"x":8,"z":1},{"x":-8,"z":1}],"ridgeDirection":"x","storeyRef":"house/main/storey-upper","spaceRef":"house/main/storey-upper/space-wing","baseElevationM":6.55,"material":"standing-seam-metal","colorHex":"#2D3435"}],"junctions":[{"ref":"roof/main/junction-original-extended","type":"valley","segmentRefs":["roof/main/segment-original-wing","roof/main/segment-extended-wing"]}]}'),
  propose_platform_update: proposal('propose_platform_update', 'Propose platform update', 'Add/remove/resize a mezzanine platform attached to a space.', '`action`, `buildingRef`, `storeyRef`, `spaceRef`, `platformRef`; optional `footprint`, `elevationM`, `thicknessM`.', '{"action":"add","buildingRef":"house/main","storeyRef":"storey/ground","spaceRef":"space/living","platformRef":"platform/mezzanine","footprint":[{"x":0,"z":0},{"x":2,"z":0},{"x":2,"z":2},{"x":0,"z":2}],"elevationM":2.5}'),
  propose_landscape_update: proposal('propose_landscape_update', 'Propose landscape polygon update', 'Add/remove/move or reshape one straight-edged landscape zone.', '`action`, `zoneRef`; optional `name`, `kind`, polygon `footprint`, or move `delta`.', '{"action":"set-footprint","zoneRef":"zone/lawn","footprint":[{"x":0,"z":8},{"x":12,"z":8},{"x":12,"z":16},{"x":0,"z":16}]}'),
  propose_plant_update: proposal('propose_plant_update', 'Propose terrain-supported plant update', 'Add/remove/move a plant whose elevation is derived from terrain.', '`action`, `plantRef`; optional `name`, `species`, `kind`, `position`.', '{"action":"move","plantRef":"plant/apple","position":{"x":10,"z":12}}'),
  propose_planting_area: proposal('propose_planting_area', 'Propose planting line or area', 'Create one deterministic, atomic planting scheme along a site/parcel boundary, a custom polyline, or inside a polygon. The tool applies offsets, spacing, rows and corner treatment; skips modeled buildings, access routes, entrances and drainage zones; and reports unmapped utility risk before approval.', '`plantingRef` and `mode` (`boundary`, `line`, or `polygon`) are required. Boundary mode accepts stable `sourceRefs` such as `site` or parcel refs. Line/polygon modes require `points`. Set `inwardOffsetM`, `spacingM`, `rowCount`, `rowSpacingM`, `cornerTreatment` (`include`, `distribute`, `skip`) and `clearanceM`. Use a planting-guide `plantingPaletteRef` or provide `species` and optional `kind`.', '{"plantingRef":"planting/hornbeam-perimeter","mode":"boundary","sourceRefs":["site"],"inwardOffsetM":1,"spacingM":0.6,"rowCount":1,"rowSpacingM":0.6,"cornerTreatment":"distribute","plantingPaletteRef":"plant-guide/hornbeam","clearanceM":1.2}'),
  propose_garden_fixture: proposal('propose_garden_fixture', 'Propose garden fixture', 'Add, remove, move or rotate one semantic fixture, or build one coordinated garden preset, through one mode-discriminated tool.', 'Input is a JSON object. For `mode: "single"`, pass `action` (`add`, `remove`, `move`, or `rotate`) and `fixtureRef`; `add` also requires `catalogId` and `position`, `move` requires `position`, and `rotate` requires `rotationDegrees`; optional `name` applies to additions. For `mode: "preset"`, pass `preset` (`starter-kitchen-garden`, `tomato-raised-bed`, `potato-raised-bed`, or `cucumber-raised-bed`) and stable `setRef`; use exact `origin` with optional `placement: "at-origin"`, or use `placement: "next-to-existing"` without `origin`. Optional `rotationDegrees` rotates the complete preset.', '{"mode":"preset","preset":"tomato-raised-bed","setRef":"fixture-set/tomato-bed-2","placement":"next-to-existing","rotationDegrees":0}'),
  manage_change_set: define({ name: 'manage_change_set', title: 'Manage draft change set', role, task: 'Create, populate, finalize, or discard one transactional change-set draft through one action-discriminated tool.', input: 'Input is a JSON object with required `action`. For `create`, pass stable `changeSetRef`, human-readable `label`, and integer `baseRevision`. For `add-operations`, pass `changeSetRef` and a non-empty `operations` array whose entries use the ProjectV2 command `type` discriminator. For `finalize` or `discard`, pass `changeSetRef` only.', tools: 'Call get_project_state before `create` and use its exact revision. Use `add-operations` for changes that must remain atomic, then `finalize` once. A draft cannot be approved; finalization creates the reviewable ghost variant. Use `discard` only for an unfinalized draft and manage_variant action `discard` for a finalized proposal.', output: `${result} Create and add actions return the draft audit; finalize returns status "variant_created" with variantRef and the complete operation audit; discard removes only the uncommitted draft.`, exampleOutput: '{"action":"create","changeSetRef":"change-set/relocate-kitchen-garden","label":"Relocate complete kitchen garden","baseRevision":1}' }),
  measure_height: define({ name: 'measure_height', title: 'Measure semantic or free height', role, task: 'Measure a reproducible vertical distance. Semantic mode resolves buildings, storeys, walls, roof, openings, slabs, platforms, spaces and ceiling finishes; free mode compares two exact picked 3D points.', input: 'For semantic mode pass `mode: "semantic"`, `objectRef`, and `measurement`: `auto`, `object-height`, `ground-to-eaves`, `ground-to-ridge`, `clear-height`, `opening-height`, or `terrain-clearance`. For free mode pass `mode: "free-vertical"`, `startPoint` and `endPoint` as local project `{x,y,z}` metres.', tools: 'This is read-only. Use get_project_state first to resolve semantic refs. Report relative height separately from local project and absolute datum elevations.', output: `${result} Returns measurement with exact semantic reference points, relative heightM, localProjectM elevations and absoluteM elevations.`, exampleOutput: '{"mode":"semantic","objectRef":"wall/upper-east","measurement":"ground-to-ridge"}' }),
  propose_climate_update: proposal('propose_climate_update', 'Propose climate update', 'Edit one month used by seasonal analysis.', '`month` (integer 1–12); optional `meanMinC`, `meanMaxC`, `temperatureByDayPartC` with required numeric `night`, `morning`, `day`, and `evening` values in °C, plus optional precipitation, sunshine, ET0, frost and wind fields. Day parts use local time: night 00–06, morning 06–12, day 12–18, evening 18–24.', '{"month":7,"temperatureByDayPartC":{"night":15.2,"morning":19.0,"day":24.1,"evening":20.2},"precipitationMm":88}'),
  show_structure_views: define({ name: 'show_structure_views', title: 'Show architectural structure views', role, task: 'Open an ephemeral visible in-page architectural report with rendered images and return structured building placement numbers. Architectural-set expands to site plan, four site-north elevations, axonometric, selected storey plans and two centreline sections.', input: '`mode` defaults to `architectural-set`; optional `buildingRefs`, `variantRef`, custom `views`, and `includeAnnotations`. Maximum 12 expanded views.', tools: 'Use get_project_state for refs. This is read-only. Images appear in the page; the JSON result contains no data URL, Blob URL or binary content.', output: `${result} Returns reportRef, views with presentation "visible-in-page", and selected building placement in local model metres.`, exampleOutput: '{"mode":"architectural-set","buildingRefs":["house/main"],"includeAnnotations":true}' }),
  run_seasonal_analysis: define({ name: 'run_seasonal_analysis', title: 'Run seasonal analysis', role, task: 'Estimate monthly night, morning, day and evening temperatures alongside daylight, water balance, frost, foliage and bloom from V2 climate and landscape state.', input: '`months` is an array of integers from 1–12 and defaults to `[1,4,7,10]`; optional string `variantRef`.', tools: 'Read-only; do not present conceptual climate values as professional weather or horticultural advice.', output: `${result} Each month includes \`temperatureByDayPartC\` with numeric \`night\`, \`morning\`, \`day\`, and \`evening\` averages in °C for the local-time windows 00–06, 06–12, 12–18, and 18–24.`, exampleOutput: '{"months":[1,4,7,10]}' }),
  compare_variants: define({ name: 'compare_variants', title: 'Compare variants', role, task: 'Compare metrics and validation issues for one to four ghost variants.', input: '`variantRefs` is an array of one to four refs.', tools: 'Read-only. Apply separately with manage_variant action `request-apply`.', output: result, exampleOutput: '{"variantRefs":["variant/a","variant/b"]}' }),
  manage_variant: define({ name: 'manage_variant', title: 'Manage variant review', role, task: 'Request human review for a current pending proposal or reject it while retaining its audit history.', input: 'Input is a JSON object with required `action` (`request-apply` or `discard`) and `variantRef` from a pending proposal. Optional `reason` is accepted only for `discard`.', tools: 'For `request-apply`, never approve for the person; wait for their Apply or Reject decision. Use get_proposals first when rediscovering a proposal. Cancellation closes the confirmation surface but keeps the proposal pending. Use `discard` for an uncommitted proposal and undo_last_change for committed work.', output: `${result} Request-apply resolves with status "applied" or "rejected" after the human decision. Discard immediately returns status "rejected" without changing the committed project. Proposal history retains either decision.`, exampleOutput: '{"action":"request-apply","variantRef":"variant/example"}' }),
  undo_last_change: define({ name: 'undo_last_change', title: 'Undo committed change', role, task: 'Undo the most recent committed ProjectV2 change.', input: 'Empty object.', tools: 'Use only when the person requests the latest committed edit to be reversed.', output: result, exampleOutput: '{}' }),
} as const

export type WebMcpToolPromptName = keyof typeof webMcpToolPrompts
