import { expect, test } from '@playwright/test'

test('ProjectV2 editor and architectural report work in one real canvas', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.addInitScript(() => {
    const tools: Record<string, { execute: (input: unknown) => Promise<{ content: Array<{ text: string }> }> }> = {}
    const revoked: string[] = []; const revoke = URL.revokeObjectURL.bind(URL)
    URL.revokeObjectURL = (url: string) => { revoked.push(url); revoke(url) }
    Object.assign(window, { __projectV2WebMcpTools: tools, __projectV2RevokedUrls: revoked })
    Object.defineProperty(document, 'modelContext', { configurable: true, value: { registerTool: async (tool: { name: string; execute: (input: unknown) => Promise<{ content: Array<{ text: string }> }> }) => { tools[tool.name] = tool } } })
  })
  await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' })

  await expect(page.locator('canvas')).toHaveCount(1)
  await expect(page.getByText('Spatial Editor', { exact: true })).toBeVisible()
  await expect(page.getByText('PROJECTV2 / SEMANTIC MODEL')).toBeVisible()
  await expect(page.getByText('Main house')).toBeVisible()
  const modernBarn = page.getByRole('button', { name: /Modern barn/ })
  await expect(modernBarn).toHaveClass(/active/)
  await expect(modernBarn).toContainText('2 levels · 45° gable')
  await expect(page.locator('.model-tree')).toContainText('2 storey')
  await expect(page.getByRole('button', { name: 'Open garden fixtures' })).toContainText('6 placed')
  const refocus = page.getByRole('button', { name: 'Refocus on Main house' })
  await expect(refocus).toBeVisible()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await refocus.click()
  await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveClass(/active/)
  await expect(page.getByRole('status')).toContainText('Camera refocused on Main house.')

  const explode = page.getByRole('button', { name: 'Explode', exact: true })
  await explode.click()
  await expect(explode).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('Exploded room view')).toContainText('3 rooms · 2 levels · roof separated')
  await expect(page.locator('.exploded-room-label')).toHaveCount(3)
  await expect(page.locator('.exploded-room-label').nth(0)).toContainText('Kitchen and studio')
  await expect(page.locator('.exploded-room-label').nth(1)).toContainText('Living room')
  await expect(page.locator('.exploded-room-label[data-storey-ref="house/main/storey-upper"]')).toContainText('Upper space')
  await page.waitForTimeout(900)
  await page.locator('.viewport').screenshot({ path: 'test-results/project-v2-exploded-rooms.png' })
  await explode.click()
  await expect(explode).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.exploded-room-label')).toHaveCount(0)

  await page.getByRole('button', { name: 'Technical' }).click()
  await expect(page.getByRole('button', { name: 'Realistic' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Angle', exact: true })).toHaveCount(0)
  const canvas = page.getByRole('application', { name: 'Interactive ProjectV2 spatial editor' })
  const canvasBounds = await canvas.boundingBox(); if (!canvasBounds) throw new Error('Canvas bounds unavailable.')
  await page.getByRole('button', { name: 'Length', exact: true }).click()
  await expect(page.getByLabel('Length measurement instructions')).toContainText('Click point 1, then point 2')
  await canvas.click({ position: { x: canvasBounds.width * 0.28, y: canvasBounds.height * 0.48 } })
  await expect(page.getByRole('status')).toContainText('First point placed. Click the second point.')
  await canvas.click({ position: { x: canvasBounds.width * 0.48, y: canvasBounds.height * 0.62 } })
  await expect(page.locator('.spatial-measurement-label.length')).toBeVisible()
  await expect(page.locator('.spatial-measurement-label.length')).toContainText(/\d+\.\d{2} m/)
  await page.getByRole('button', { name: 'Area', exact: true }).click()
  await expect(page.getByLabel('Area measurement instructions')).toContainText('Hold and drag a rectangle on the ground')
  await page.mouse.move(canvasBounds.x + canvasBounds.width * 0.2, canvasBounds.y + canvasBounds.height * 0.42)
  await page.mouse.down()
  await page.mouse.move(canvasBounds.x + canvasBounds.width * 0.46, canvasBounds.y + canvasBounds.height * 0.64, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.spatial-measurement-label.area')).toBeVisible()
  await expect(page.locator('.spatial-measurement-label.area')).toContainText(/\d+\.\d{2} m²/)
  await page.locator('.viewport').screenshot({ path: 'test-results/project-v2-area-measurement.png' })
  await page.getByLabel('Area measurement instructions').getByRole('button', { name: 'Clear' }).click()
  await expect(page.locator('.spatial-measurement-label.area')).toBeHidden()
  for (const mode of ['Section', 'Plan', 'Edit']) await page.getByRole('button', { name: mode, exact: true }).click()
  await page.locator('.viewport').screenshot({ path: 'test-results/project-v2-editor.png' })

  await page.getByRole('button', { name: 'Open garden fixtures' }).click()
  const fixtures = page.getByRole('region', { name: 'Garden fixture library' })
  await expect(fixtures).toBeVisible()
  await expect(fixtures.locator('.fixture-row')).toHaveCount(4)
  await expect(fixtures).toContainText('Starter kitchen garden')
  await expect(fixtures).toContainText('Tomato row')
  await expect(fixtures).toContainText('Potato row')
  await expect(fixtures).toContainText('Cucumber trellis')
  await expect(page.getByRole('status')).toContainText('Camera focused on the placed garden fixtures.')
  await page.waitForTimeout(700)
  await fixtures.screenshot({ path: 'test-results/project-v2-garden-fixtures.png' })
  await fixtures.getByRole('button', { name: 'View placed' }).click()
  await expect(fixtures).toBeHidden()
  await page.waitForTimeout(700)
  await page.locator('.viewport').screenshot({ path: 'test-results/project-v2-garden-scene.png' })

  await page.getByRole('button', { name: 'Climate' }).click()
  const climate = page.getByRole('region', { name: 'Monthly temperature by part of day' })
  await expect(climate).toBeVisible()
  await expect(climate.getByText('Temperature through the day')).toBeVisible()
  await expect(climate.locator('.climate-table tbody tr')).toHaveCount(12)
  await expect(climate.locator('.daypart-readout')).toContainText('Night')
  await expect(climate.locator('.daypart-readout')).toContainText('Morning')
  await expect(climate.locator('.daypart-readout')).toContainText('Day')
  await expect(climate.locator('.daypart-readout')).toContainText('Evening')
  await climate.getByRole('button', { name: 'Show Jan climate in the scene' }).click()
  await expect(climate.locator('.climate-detail')).toContainText('JAN / MONTH 1')
  await climate.screenshot({ path: 'test-results/project-v2-climate-dayparts.png' })
  await climate.getByRole('button', { name: 'Close climate panel' }).click()
  await expect(climate).toBeHidden()

  await page.getByRole('button', { name: 'Planting' }).click()
  const planting = page.getByRole('region', { name: 'Planting guide and soil analysis' })
  await expect(planting).toBeVisible()
  await expect(planting.getByText('Known ground conditions')).toBeVisible()
  await expect(planting.getByText('Tomato', { exact: true })).toBeVisible()
  await expect(planting.getByText('Potato', { exact: true })).toBeVisible()
  await expect(planting.getByText('Cucumber', { exact: true })).toBeVisible()
  await expect(planting.getByText('Apple tree', { exact: true })).toBeVisible()
  await expect(planting.getByText('Sour cherry', { exact: true })).toBeVisible()
  await expect(planting.getByText('pH and fertility')).toBeVisible()
  await planting.screenshot({ path: 'test-results/project-v2-planting-guide.png' })
  await planting.getByRole('button', { name: 'Close planting guide' }).click()
  await expect(planting).toBeHidden()

  await page.getByRole('button', { name: 'MCP Tools' }).click()
  const catalog = page.getByRole('region', { name: 'WebMCP tool catalog' })
  await expect(catalog).toBeVisible()
  await expect(catalog.locator('.tool-browser nav button')).toHaveCount(23)
  await expect(catalog.getByRole('link', { name: 'Open JSON' })).toHaveAttribute('href', /webmcp-tools\.json$/)
  await catalog.getByRole('searchbox', { name: 'Search tools' }).fill('run_seasonal_analysis')
  await expect(catalog.locator('.tool-browser nav button')).toHaveCount(1)
  await expect(catalog.locator('.tool-detail')).toContainText('Run seasonal analysis')
  await expect(catalog.locator('.tool-document')).toContainText('<role>')
  await expect(catalog.locator('.tool-document')).toContainText('<example_output>')
  await catalog.getByRole('button', { name: 'Input schema' }).click()
  await expect(catalog.locator('.tool-document')).toContainText('months')
  await catalog.getByRole('button', { name: 'Example' }).click()
  await expect(catalog.locator('.tool-document')).toContainText('1')
  await catalog.getByRole('button', { name: 'Result shape' }).click()
  await expect(catalog.locator('.tool-document')).toContainText('temperatureByDayPartC')
  const manifestSummary = await page.evaluate(async () => {
    const value = await fetch('/webmcp-tools.json').then((response) => response.json()) as { toolCount: number; source: string; tools: Array<{ name: string }> }
    return {
      toolCount: value.toolCount,
      source: value.source,
      gardenTools: value.tools.map((tool) => tool.name).filter((name) => name.includes('garden_fixture')),
    }
  })
  expect(manifestSummary).toEqual({
    toolCount: 23,
    source: 'runtime-zod-and-structured-prompts',
    gardenTools: ['list_garden_fixtures', 'propose_garden_fixture_update', 'propose_garden_fixture_set'],
  })
  await page.waitForFunction(() => Boolean((window as unknown as { __projectV2WebMcpTools?: Record<string, unknown> }).__projectV2WebMcpTools?.list_garden_fixtures))
  const liveGardenFixtureProof = await page.evaluate(async () => {
    const tools = (window as unknown as { __projectV2WebMcpTools: Record<string, { execute: (input: unknown) => Promise<{ content: Array<{ text: string }> }> }> }).__projectV2WebMcpTools
    const catalog = JSON.parse((await tools.list_garden_fixtures.execute({})).content[0].text) as { data: Array<{ id: string }> }
    const proposal = JSON.parse((await tools.propose_garden_fixture_set.execute({ preset: 'tomato-raised-bed', setRef: 'fixture-set/browser-tomato-2', placement: 'next-to-existing', rotationDegrees: 0 })).content[0].text) as { status: string; metrics: { fixtureCount: number } }
    const state = JSON.parse((await tools.get_project_state.execute({ detail: 'landscape' })).content[0].text) as { data: { landscape: { fixtures: unknown[] } } }
    return { catalogIds: catalog.data.map((fixture) => fixture.id), proposalStatus: proposal.status, proposedFixtureCount: proposal.metrics.fixtureCount, committedFixtureCount: state.data.landscape.fixtures.length }
  })
  expect(liveGardenFixtureProof).toEqual({
    catalogIds: ['raised-bed-2x1', 'tomato-row', 'potato-row', 'cucumber-trellis'],
    proposalStatus: 'variant_created',
    proposedFixtureCount: 8,
    committedFixtureCount: 6,
  })
  await catalog.screenshot({ path: 'test-results/project-v2-mcp-tools.png' })
  await catalog.getByRole('button', { name: 'Close MCP tools' }).click()
  await expect(catalog).toBeHidden()

  await page.getByRole('button', { name: 'Architectural set' }).click()
  const report = page.getByRole('region', { name: 'Architectural structure report' })
  await expect(report).toBeVisible({ timeout: 60_000 })
  await expect(report.locator('.thumbs button')).toHaveCount(10)
  await expect(report.locator('.thumbs button span')).toHaveText(['Site plan', 'North elevation', 'South elevation', 'East elevation', 'West elevation', 'Axonometric overview', 'Ground storey plan', 'Upper storey plan', 'Longitudinal section', 'Transverse section'])
  await expect(report.locator('.placement tbody tr')).toHaveCount(1)
  await expect(report.locator('.placement tbody')).toContainText('Main house')
  await expect(report.locator('.placement tbody')).toContainText('-1.00 / -1.00 m')
  await expect(report.locator('.drawing img')).toHaveAttribute('src', /^blob:/)
  await report.screenshot({ path: 'test-results/project-v2-architectural-report.png' })

  await report.getByRole('button', { name: 'Close report' }).click()
  await expect(report).toBeHidden()
  await expect.poll(() => page.evaluate(() => (window as unknown as { __projectV2RevokedUrls: string[] }).__projectV2RevokedUrls.length)).toBe(10)
  await page.waitForFunction(() => Boolean((window as unknown as { __projectV2WebMcpTools?: Record<string, unknown> }).__projectV2WebMcpTools?.show_structure_views))
  const variantResult = await page.evaluate(async () => {
    const tools = (window as unknown as { __projectV2WebMcpTools: Record<string, { execute: (input: unknown) => Promise<{ content: Array<{ text: string }> }> }> }).__projectV2WebMcpTools
    const proposal = JSON.parse((await tools.propose_building_update.execute({ action: 'move', buildingRef: 'house/main', position: { x: 2, z: -1 } })).content[0].text)
    const result = JSON.parse((await tools.show_structure_views.execute({ mode: 'custom', variantRef: proposal.variantRef, views: [{ type: 'axonometric' }] })).content[0].text)
    const state = JSON.parse((await tools.get_project_state.execute({ detail: 'summary' })).content[0].text)
    return { result, revisionAfterReport: state.projectRevision }
  })
  expect(JSON.stringify(variantResult.result)).not.toMatch(/blob:|data:image|imageUrl/)
  expect(variantResult.revisionAfterReport).toBe(1)
  await expect(report).toBeVisible({ timeout: 60_000 })
  await expect(report.locator('.thumbs button')).toHaveCount(1)
  await expect(report.locator('.placement tbody')).toContainText('2.00 / -1.00 m')
  await report.getByRole('button', { name: 'Close report' }).click()
  await expect(report).toBeHidden()
  await expect.poll(() => page.evaluate(() => (window as unknown as { __projectV2RevokedUrls: string[] }).__projectV2RevokedUrls.length)).toBe(11)
  await expect(page.locator('canvas')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('house remains visible when zoomed out across the long plot', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.setViewportSize({ width: 1059, height: 1270 })
  await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' })
  const viewport = page.locator('.viewport'); await expect(viewport).toBeVisible()
  await expect(viewport.locator('canvas')).toHaveCount(1)
  const box = await viewport.boundingBox(); if (!box) throw new Error('Viewport bounds unavailable.')
  const canvas = viewport.locator('canvas')
  await canvas.hover()
  const beforeKeyboardPan = await viewport.screenshot()
  await page.keyboard.press('ArrowUp')
  await page.waitForTimeout(500)
  const afterKeyboardPan = await viewport.screenshot()
  expect(Buffer.compare(beforeKeyboardPan, afterKeyboardPan)).not.toBe(0)
  const middleDragStart = await viewport.screenshot()
  await page.mouse.move(box.x + box.width * 0.72, box.y + box.height * 0.72)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(box.x + box.width * 0.55, box.y + box.height * 0.58, { steps: 8 })
  await page.mouse.up({ button: 'middle' })
  await page.waitForTimeout(500)
  const middleDragEnd = await viewport.screenshot()
  expect(Buffer.compare(middleDragStart, middleDragEnd)).not.toBe(0)
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.wheel(0, 1000)
  await page.waitForTimeout(700)
  await viewport.screenshot({ path: 'test-results/project-v2-zoomed-out.png' })
  await expect(page.getByLabel('Garden navigation controls')).toContainText('hold wheel + drag')
  await expect(page.getByLabel('Land-use legend')).toContainText('Garden / agricultural land')
  await expect(page.getByRole('button', { name: 'Refocus on Main house' })).toBeVisible()
  expect(errors).toEqual([])
})
