import { expect, test } from '@playwright/test'

test('reference house opens at measured scale, renders both floors and preserves edits on reopening', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message))
  await page.addInitScript(() => {
    const tools: Record<string, unknown> = {}
    Object.assign(window, { __referenceTools: tools })
    Object.defineProperty(document, 'modelContext', { configurable: true, value: { registerTool: async (tool: { name: string }) => { tools[tool.name] = tool } } })
  })
  await page.goto(process.env.APP_URL ?? 'http://127.0.0.1:5173')
  await page.getByRole('button', { name: /Dom z planów · Reference house/ }).click()
  await page.getByRole('button', { name: 'House interior', exact: true }).click()
  const rooms = page.getByRole('region', { name: 'Rooms on this level' })
  await expect(rooms).toContainText('86.37 m²')
  await expect(rooms).toContainText('45.14 m²')
  await page.getByRole('button', { name: 'Hide catalog', exact: true }).click()
  await page.waitForTimeout(1800)
  await page.screenshot({ path: 'test-results/reference-ground-3d.png' })
  await page.getByRole('button', { name: '2D Plan', exact: true }).click()
  await expect(page.locator('.interior-dimension').filter({ hasText: '7.28 m' })).toBeVisible()
  await expect(page.locator('.interior-dimension').filter({ hasText: '6.20 m' })).toBeVisible()
  await expect(page.locator('.interior-dimension').filter({ hasText: '10.79 m' })).toBeVisible()
  await page.screenshot({ path: 'test-results/reference-ground-plan.png' })
  await rooms.getByRole('button', { name: /Garaż/ }).click()
  await expect(page.getByRole('spinbutton', { name: 'Room width (m)' })).toHaveValue('7.28')
  await expect(page.getByRole('spinbutton', { name: 'Room depth (m)' })).toHaveValue('6.2')
  await page.getByRole('textbox', { name: 'Room name', exact: true }).fill('Garaż rodzinny')
  await page.getByRole('button', { name: 'Save room', exact: true }).click()
  await page.getByRole('region', { name: 'Placed objects' }).getByRole('button', { name: /Wyspa 1.28/ }).click()
  await expect(page.getByRole('spinbutton', { name: 'Width (m)', exact: true })).toHaveValue('1.28')
  await expect(page.getByRole('spinbutton', { name: 'Depth (m)', exact: true })).toHaveValue('2.92')
  await page.getByRole('button', { name: /1 Piętro/ }).click()
  await expect(rooms.getByRole('button')).toHaveCount(7)
  await expect(rooms).toContainText('40.65 m²')
  await expect(rooms).toContainText('14.33 m²')
  await expect(page.getByRole('region', { name: 'Placed objects' }).getByRole('button')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/reference-upper-plan.png' })
  await page.getByRole('button', { name: '3D Interior', exact: true }).click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: 'test-results/reference-upper-3d.png' })
  await page.getByText('Plan dimensions & source notes', { exact: true }).click()
  await expect(page.locator('.interior-reference-notes')).toContainText('provisional 2.80 m')
  await page.getByText('Plan dimensions & source notes', { exact: true }).click()
  await page.reload()
  // The template entry must continue the saved work, never overwrite its room names or contents.
  await page.getByRole('button', { name: /Dom z planów · Reference house/ }).click()
  await page.getByRole('button', { name: 'House interior', exact: true }).click()
  await expect(rooms).toContainText('Garaż rodzinny')
  await expect(page.getByRole('region', { name: 'Placed objects' }).getByRole('button')).toHaveCount(21)
  const structure = await page.evaluate(async () => {
    const tools = (window as unknown as { __referenceTools: Record<string, { execute: (args: unknown) => Promise<{ content: { text: string }[] }> }> }).__referenceTools
    return JSON.parse((await tools.get_project_state.execute({ detail: 'structure' })).content[0].text).data
  })
  expect(structure.buildings[0].stairs).toHaveLength(1)
  expect(structure.buildings[0].slabs[1].holes).toHaveLength(1)
  expect(structure.buildings[0].furniture).toHaveLength(22)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '3D Interior', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.body.scrollWidth)).toBe(390)
  await page.screenshot({ path: 'test-results/reference-mobile.png' })
  expect(errors).toEqual([])
})
